// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoBeZtzKIM4tJ4HUnkrFwsCKGlvz5GmgA',
    appId: '1:872183862119:web:8d11d379226694297615c2',
    messagingSenderId: '872183862119',
    projectId: 'movies-80e04',
    authDomain: 'movies-80e04.firebaseapp.com',
    storageBucket: 'movies-80e04.firebasestorage.app',
    measurementId: 'G-C7SLZ0T6S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5H8A76vzasraSPzclHetyzXKJ7FsT86s',
    appId: '1:872183862119:android:5893610608204f867615c2',
    messagingSenderId: '872183862119',
    projectId: 'movies-80e04',
    storageBucket: 'movies-80e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKLoguDgMDKngABqtKF2eXPRiKj8m8kI',
    appId: '1:872183862119:ios:85555a9e9d28ed617615c2',
    messagingSenderId: '872183862119',
    projectId: 'movies-80e04',
    storageBucket: 'movies-80e04.firebasestorage.app',
    iosClientId: '872183862119-kaedn0o5et14pjve46f2rcqlsg4ef47j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdKLoguDgMDKngABqtKF2eXPRiKj8m8kI',
    appId: '1:872183862119:ios:85555a9e9d28ed617615c2',
    messagingSenderId: '872183862119',
    projectId: 'movies-80e04',
    storageBucket: 'movies-80e04.firebasestorage.app',
    iosClientId: '872183862119-kaedn0o5et14pjve46f2rcqlsg4ef47j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoBeZtzKIM4tJ4HUnkrFwsCKGlvz5GmgA',
    appId: '1:872183862119:web:c9bde73dc89da13c7615c2',
    messagingSenderId: '872183862119',
    projectId: 'movies-80e04',
    authDomain: 'movies-80e04.firebaseapp.com',
    storageBucket: 'movies-80e04.firebasestorage.app',
    measurementId: 'G-1BBLSCEKTD',
  );
}
